name: Auto Publish CI
on:
 pull_request:

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Env
        run: |
          python3 -m pip install -r requirements.txt
      - name: CI
        run: python3 src/main.py ${{ secrets.TOKEN }} debug
